### ISSUE TITLE
Idea: Support RxJS/BaconJS

### ISSUE THREAD

**Issue by richardanaya** [cshum/caco#1]
One way you might be able to have an edge of the co guys is to support these popular libraries.

https://github.com/tj/co/pull/221

Someone tried to commit support, but decided against it.  Not sure what your aims are of this library! But just a suggestion.

**Comment by cshum** [comment]
This is interesting. 

Speaking of yieldable value, it should be pretty straightforward to accept a optional mapper argument. 
So that one can customize anything to be yieldable.

The mapper function looks something like
```js
function mapYieldable (val, cb) {
  if (isPromise(val)) {
    val.then(function (val) {
      cb(null, val)
    }, cb)
    return true // acknowledge val to be yieldable
  } 
  if (isObservable(val)) {
    ...
    return true
  }
  if (isOtherYieldableStuff(val)) {
    ...
    return true
  }
}
```
